if(EXISTS "C:/Users/Lenovo/Music/Zepra/build-win/test/zeprascript/zeprascript-integration-tests[1]_tests.cmake")
  include("C:/Users/Lenovo/Music/Zepra/build-win/test/zeprascript/zeprascript-integration-tests[1]_tests.cmake")
else()
  add_test(zeprascript-integration-tests_NOT_BUILT zeprascript-integration-tests_NOT_BUILT)
endif()
